# Generated by Django 6.0.1 on 2026-01-07 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True)),
                ('value', models.TextField()),
                ('type', models.CharField(choices=[('text', 'Text'), ('textarea', 'Text Area'), ('email', 'Email'), ('url', 'URL'), ('boolean', 'Boolean')], default='text', max_length=10)),
                ('category', models.CharField(default='general', max_length=50)),
                ('display_order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['category', 'display_order'],
            },
        ),
    ]
