# Generated by Django 6.0.1 on 2026-01-07 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Pixel & Brand', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('logo_only', models.BooleanField(default=False, help_text='Show only logo without text')),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('company_address', models.TextField(blank=True)),
                ('tagline', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
