# Generated by Django 6.0.1 on 2026-01-07 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0002_sitesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSetting',
        ),
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Site Settings', 'verbose_name_plural': 'Site Settings'},
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='logo_only',
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='logo_alt_text',
            field=models.CharField(blank=True, default='Pixel & Brand Logo', help_text="Description of the logo for accessibility (shown if logo doesn't load)", max_length=200, verbose_name='Logo Alt Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='show_logo_only',
            field=models.BooleanField(default=False, help_text='Check this to show only the logo without company name text', verbose_name='Show Only Logo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_address',
            field=models.TextField(blank=True, default='Craftrix Consultancy Services Pvt Ltd, Udarasiromani Rd, Thiruvananthapuram, Kerala 695010', help_text='Full company address for contact section', verbose_name='Company Address'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='company_name',
            field=models.CharField(default='Pixel & Brand', help_text='The name of your company that appears throughout the site', max_length=200, verbose_name='Company Name'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(blank=True, default='info@craftrix.com', help_text='Contact email displayed in header/footer', max_length=254, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(blank=True, default='+91 80864-88003', help_text='Contact phone number displayed in header/footer', max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=models.ImageField(blank=True, help_text='Upload your company logo. Recommended size: 200x60px', null=True, upload_to='logos/', verbose_name='Company Logo'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='tagline',
            field=models.CharField(blank=True, default='Digital Marketing Agency in Kerala', help_text='Short tagline that appears in footer and page titles', max_length=200, verbose_name='Company Tagline'),
        ),
    ]
