# Generated by Django 6.0.1 on 2026-01-07 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0003_delete_sitesetting_alter_sitesettings_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cta_description',
            field=models.TextField(blank=True, default="Let's work together to create amazing digital experiences.", help_text='Call-to-action description text', verbose_name='CTA Description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='cta_title',
            field=models.CharField(blank=True, default='Ready to Grow Your Business?', help_text='Call-to-action title on the homepage', max_length=200, verbose_name='CTA Title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_title',
            field=models.CharField(blank=True, default='Transform Your Digital Presence', help_text='Main title on the homepage hero section', max_length=200, verbose_name='Hero Title'),
        ),
    ]
