# Generated by Django 5.2.7 on 2026-01-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0004_sitesettings_cta_description_sitesettings_cta_title_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='hero_description',
            field=models.TextField(blank=True, default='We help businesses grow their brand, connect with their audience, and drive real results through comprehensive digital marketing solutions.', help_text='Description text on the homepage hero section', verbose_name='Hero Description'),
        ),
    ]
