# Generated by Django 6.0.1 on 2026-01-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agency', '0005_sitesettings_hero_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='cta_button_text',
            field=models.CharField(blank=True, default='Get In Touch', help_text='Text for the call-to-action button', max_length=50, verbose_name='CTA Button Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_button_text',
            field=models.CharField(blank=True, default='Get Started Today', help_text='Text for the hero section button', max_length=50, verbose_name='Hero Button Text'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Image for the hero section (recommended: 800x600px)', null=True, upload_to='homepage/', verbose_name='Hero Image'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='portfolio_description',
            field=models.TextField(blank=True, default='Explore our portfolio of successful digital marketing projects and brand transformations.', help_text='Description for the portfolio section', verbose_name='Portfolio Description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='portfolio_title',
            field=models.CharField(blank=True, default='Our Recent Work', help_text='Title for the portfolio section', max_length=200, verbose_name='Portfolio Title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_description',
            field=models.TextField(blank=True, default='End-to-end digital solutions to grow your brand, connect with your audience, and drive real results.', help_text='Description for the services section', verbose_name='Services Description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='services_title',
            field=models.CharField(blank=True, default='Our Services', help_text='Title for the services section', max_length=200, verbose_name='Services Title'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonials_description',
            field=models.TextField(blank=True, default='Hear from businesses that have transformed their digital presence with our solutions.', help_text='Description for the testimonials section', verbose_name='Testimonials Description'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='testimonials_title',
            field=models.CharField(blank=True, default='What Our Clients Say', help_text='Title for the testimonials section', max_length=200, verbose_name='Testimonials Title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cta_description',
            field=models.TextField(blank=True, default="Let's work together to create amazing digital experiences that drive results.", help_text='Description for the call-to-action section', verbose_name='CTA Description'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='cta_title',
            field=models.CharField(blank=True, default='Ready to Grow Your Business?', help_text='Title for the call-to-action section', max_length=200, verbose_name='CTA Title'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='hero_description',
            field=models.TextField(blank=True, default='We help businesses grow their online presence with cutting-edge digital marketing strategies tailored to your goals.', help_text='Description under the hero title', verbose_name='Hero Description'),
        ),
    ]
