# Generated by Django 6.0.1 on 2026-01-07 15:11

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='portfolioitem',
            options={'ordering': ['display_order'], 'verbose_name': 'Portfolio Item', 'verbose_name_plural': 'Portfolio Items'},
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='detailed_description',
            field=ckeditor.fields.RichTextField(blank=True),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='portfolio/'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='project_url',
            field=models.URLField(blank=True, verbose_name='Project URL/Live Demo'),
        ),
        migrations.AddField(
            model_name='portfolioitem',
            name='technologies',
            field=models.CharField(blank=True, help_text='Comma-separated list of technologies used', max_length=200),
        ),
    ]
