# Generated by Django 6.0.1 on 2026-01-07 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_title', models.CharField(default='Transform Your Digital Presence', help_text='Main headline on the homepage', max_length=200, verbose_name='Hero Title')),
                ('hero_description', models.TextField(default='We help businesses grow their online presence with cutting-edge digital marketing strategies tailored to your goals.', help_text='Subtitle text under the hero title', verbose_name='Hero Description')),
                ('hero_button_text', models.CharField(default='Get Started Today', help_text='Text for the call-to-action button', max_length=50, verbose_name='Hero Button Text')),
                ('hero_image', models.ImageField(blank=True, help_text='Image for the hero section (recommended: 800x600px)', null=True, upload_to='homepage/', verbose_name='Hero Image')),
                ('services_section_title', models.CharField(default='Our Services', help_text='Title for the services section', max_length=200, verbose_name='Services Section Title')),
                ('services_section_description', models.TextField(default='End-to-end digital solutions to grow your brand, connect with your audience, and drive real results.', help_text='Description for the services section', verbose_name='Services Section Description')),
                ('testimonials_section_title', models.CharField(default='What Our Clients Say', help_text='Title for the testimonials section', max_length=200, verbose_name='Testimonials Section Title')),
                ('testimonials_section_description', models.TextField(default='Hear from businesses that have transformed their digital presence with our solutions.', help_text='Description for the testimonials section', verbose_name='Testimonials Section Description')),
                ('portfolio_section_title', models.CharField(default='Our Recent Work', help_text='Title for the portfolio section', max_length=200, verbose_name='Portfolio Section Title')),
                ('portfolio_section_description', models.TextField(default='Explore our portfolio of successful digital marketing projects and brand transformations.', help_text='Description for the portfolio section', verbose_name='Portfolio Section Description')),
                ('cta_section_title', models.CharField(default='Ready to Grow Your Business?', help_text='Title for the call-to-action section', max_length=200, verbose_name='CTA Section Title')),
                ('cta_section_description', models.TextField(default="Let's work together to create amazing digital experiences that drive results.", help_text='Description for the call-to-action section', verbose_name='CTA Section Description')),
                ('cta_section_button_text', models.CharField(default='Get In Touch', help_text='Text for the call-to-action button', max_length=50, verbose_name='CTA Button Text')),
                ('meta_title', models.CharField(blank=True, help_text='Page title for SEO', max_length=200, verbose_name='Meta Title')),
                ('meta_description', models.TextField(blank=True, help_text='Page description for SEO (150-160 characters recommended)', verbose_name='Meta Description')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable this homepage configuration', verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Home Page Settings',
                'verbose_name_plural': 'Home Page Settings',
            },
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['display_order'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True, help_text='Short description for cards on homepage (max 150 characters)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='content',
            field=models.TextField(help_text='Detailed content for service detail page'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Full description for service detail page'),
        ),
    ]
