# Generated by Django 6.0.1 on 2026-01-07 14:06

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_homepagesettings_alter_service_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HomePageSettings',
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ['display_order', 'title'], 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
        migrations.AddField(
            model_name='service',
            name='featured_image',
            field=models.ImageField(blank=True, help_text='Large featured image for service detail page (recommended: 800x400px)', null=True, upload_to='service-featured/', verbose_name='Featured Image'),
        ),
        migrations.AddField(
            model_name='service',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload an icon or image for this service. Recommended: 100x100px transparent PNG', null=True, upload_to='service-icons/', verbose_name='Service Icon/Image'),
        ),
        migrations.AddField(
            model_name='service',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this service on homepage'),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description (150-160 characters recommended)', max_length=160),
        ),
        migrations.AddField(
            model_name='service',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title (if empty, uses service title)', max_length=200),
        ),
        migrations.AlterField(
            model_name='service',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(help_text='Detailed content for service page with full formatting options'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Main description shown on service cards and detail pages'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, default='fas fa-chart-line', help_text="Font Awesome icon class (e.g., 'fas fa-chart-line'). Only used if no image is uploaded.", max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True, help_text='Brief description shown in service cards (max 150 characters)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
