# Generated by Django 6.0.1 on 2026-01-07 15:27

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_delete_homepagesettings_alter_service_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='content',
        ),
        migrations.AddField(
            model_name='service',
            name='basic_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Basic Plan Price'),
        ),
        migrations.AddField(
            model_name='service',
            name='benefits',
            field=models.TextField(blank=True, help_text='Benefits (one per line)'),
        ),
        migrations.AddField(
            model_name='service',
            name='detailed_content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Detailed content with features, benefits, process, etc.'),
        ),
        migrations.AddField(
            model_name='service',
            name='enterprise_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Enterprise Plan Price'),
        ),
        migrations.AddField(
            model_name='service',
            name='has_pricing',
            field=models.BooleanField(default=False, help_text='Show pricing options for this service'),
        ),
        migrations.AddField(
            model_name='service',
            name='key_features',
            field=models.TextField(blank=True, help_text='Key features (one per line)'),
        ),
        migrations.AddField(
            model_name='service',
            name='premium_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Premium Plan Price'),
        ),
        migrations.AddField(
            model_name='service',
            name='process',
            field=models.TextField(blank=True, help_text='Our process (one per line)'),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=ckeditor.fields.RichTextField(help_text='Full description shown on service detail page'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, default='fas fa-chart-line', help_text='Font Awesome icon (used if no image uploaded)', max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon_image',
            field=models.ImageField(blank=True, help_text='Upload an icon/image (100x100px PNG recommended)', null=True, upload_to='service-icons/', verbose_name='Service Icon'),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.TextField(blank=True, help_text='Brief description shown on cards (max 150 characters)'),
        ),
    ]
